// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://abnghmstbttfdgcaehgt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFibmdobXN0YnR0ZmRnY2FlaGd0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIxNDMzOTksImV4cCI6MjA2NzcxOTM5OX0.NYjzNCxYhNj39UUJfIMbsjMEC8lYohhwbWQUw6RweIU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});